### ISSUE TITLE
log error with laravel 5.6 and Windows

### ISSUE THREAD

**Issue by dryaner** [rollbar/rollbar-php-laravel#48] opened 2018-05-10 17:37 UTC
I'm following the installation instructions in laravel 5.6 and php 7.2.4. 
The Rollbar provider is loaded properly y put this in my Handler to test everything.
  public function report(Exception $exception)
  ```
  {
        \Log::error($exception);
        return parent::report($exception);
    }
```
but i don't obtain any log in rollbar and my laravel log is thowing this error

```
 [2018-05-10 12:22:57] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:181)
[stacktrace]
#0 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(115): Illuminate\\Log\\LogManager->resolve(NULL)
#1 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(103): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(602): Illuminate\\Log\\LogManager->driver()
#3 C:\\git\\geos-api\\vendor\
ollbar\
ollbar-laravel\\src\\RollbarServiceProvider.php(45): Illuminate\\Log\\LogManager->__call('listen', Array)
#4 [internal function]: Rollbar\\Laravel\\RollbarServiceProvider->boot()
#5 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#6 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(794): Illuminate\\Container\\Container->call(Array)
#10 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(777): Illuminate\\Foundation\\Application->bootProvider(Object(Rollbar\\Laravel\\RollbarServiceProvider))
#11 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Rollbar\\Laravel\\RollbarServiceProvider), 15)
#12 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(778): array_walk(Array, Object(Closure))
#13 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#14 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(206): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#15 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#16 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#17 C:\\git\\geos-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#18 C:\\git\\geos-api\\public\\index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#19 {main}
"} 

```

Any help??

**Comment by gavinr** [comment] 2018-09-10 12:40
I am getting a similar issue. I am on PHP version `7.2.8` and laravel version `5.6.31`. 

```
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Rollbar\\Laravel\\MonologHandler must be an instance of Monolog\\Handler\\HandlerInterface at /var/....................../vendor/laravel/framework/src/Illuminate/Log/LogManager.php:334)
```

Is this the same issue?

**Comment by ArturMoczulski** [comment] 2018-09-14 19:08
Hey guys. I've been working on reproducing this issue, but with little success so far. @gavinr can you tell me more about how you have your SDK configured? I'm not seeing such problems on `7.2.8` and `5.6.31`

**Comment by ArturMoczulski** [comment] 2018-10-08 11:56
@TiagoGouvea did you follow setup steps for Laravel `5.6` from the docs? The configuration looks different for Laravel <= `5.5` so it might be confusing. Just want to double check you're using `config/logging.php` if you're using Laravel `5.6`

**Comment by jessewgibbs** [comment] 2018-10-19 16:19
I'm closing this since the reporter has not responded.

**Closed by jessewgibbs** 2018-10-19 16:19 UTC
Labels: bug

**Comment by TiagoGouvea** [comment] 2018-10-26 17:58
Sorry for delay @ArturMoczulski .  I followed the 5.6 docs now and it's working fine. Thanks.
