### ISSUE TITLE
Critical: #690 E_ERROR: Call to a member function getStatus() on null when upgrading from 2.3.0 to 2.4.0 using Laravel 5.2 

### ISSUE THREAD

**Issue by bduerring** [rollbar/rollbar-php-laravel#67] opened 2018-10-04 18:18 UTC
After our last composer update, rollbar/rollbar-laravel was upgraded from 2.3.0 to 2.4.0.  Immediately following, Rollbar began reporting critical errors pertaining to RollbarServiceProvider.php

Here's the log entry:
`production.ERROR: exception 'Symfony\\Component\\Debug\\Exception\\FatalErrorException' with message 'Call to a member function getStatus() on null' in /var/app/current/vendor/rollbar/rollbar-laravel/src/RollbarServiceProvider.php:50\nStack trace:\n#0 {main}`

Forcing composer.json to 2.3.0 using "rollbar/rollbar-laravel": "2.3.0" and running composer update resolves the issue.

![screen shot 2018-10-04 at 2 08 45 pm](https://user-images.githubusercontent.com/11822986/46494147-20b2f180-c7e0-11e8-827e-c5e6f5073e1a.png)

For reference we're running Laravel Framework version 5.2.45 and PHP 5.6.24

**Comment by snipe** [comment] 2018-10-04 18:32
This is a duplicate of #65

**Comment by closca** [comment] 2018-10-04 18:37
In my case, I have locked in composer.json to 2.3.0 and seems to be fine for now.

**Comment by ArturMoczulski** [comment] 2018-10-04 23:20
@bduerring thank you for reporting. The issue has been resolved and released in https://github.com/rollbar/rollbar-php-laravel/releases/tag/v2.4.1

Although, the fact that you are getting a null as a response in the first place is concerning. Can you tell me more about your setup of the SDK? What is your setup in `config/app.php`, especially the `level` key of the `rollbar` config array? Also, what is the log or error that triggered this exception in the first place - specifically the `level` passed to the log method?

**Comment by bduerring** [comment] 2018-10-05 12:45
@ArturMoczulski, thanks for the release, will test shortly.  Happy to help regarding the details of our implementation. 

config/app.php setup:
```
'providers' => [
*truncated*
Rollbar\Laravel\RollbarServiceProvider::class,
Fideloper\Proxy\TrustedProxyServiceProvider::class
],
```

Level is defined in our .env file:
`ROLLBAR_LEVEL=error`

And utilized in the conf/services.php file:
```
rollbar' => [
    'access_token' => env('ROLLBAR_TOKEN'),
    'level' => env('ROLLBAR_LEVEL'),
    ],
```
The interesting part of this is that no exception was thrown (hence the 'null' value), so I'm not sure why Rollbar was triggered.

Kindly advise if I can provide anything else, and thanks!

**Comment by ArturMoczulski** [comment] 2018-10-08 11:20
Rollbar might be triggered by calls to the `\Log` as well depending on your setup. Perhaps your app calls `\Log` somewhere explicitly?

**Comment by bduerring** [comment] 2018-10-08 13:15
@ArturMoczulski,  we utilize Log::[level] throughout the application.  It was my understanding that the .env ROLLBAR_LEVEL setting of 'error' would only trigger rollbar if the entry was "Log::error", if that's not the case or we're doing something against best-practices, please let me know, and thanks!

**Comment by ArturMoczulski** [comment] 2018-10-31 12:51
@bduerring that is correct, I also just tested this to make sure everything works as expected in the latest release.

Are you still getting a Rollbar triggered randomly (with no exceptions thrown)?

**Comment by ArturMoczulski** [comment] 2018-12-17 05:00
I'm closing this issue due to no feedback

**Closed by ArturMoczulski** 2018-12-17 05:00 UTC
Labels: bug
